<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>From.IdentityKafkaEvents</Title>
        <Authors>nikitaberezhko</Authors>
        <RepositoryUrl>https://gitlab.com/carsharing-backend/contracts/kafka/fromidentitykafkaevents</RepositoryUrl>
        <Version>1.0.1</Version>
    </PropertyGroup>

</Project>
